USE [master]
GO

/****** Object:  Database [PDADB]    Script Date: 16-3-2024 16:44:20 ******/
CREATE DATABASE [PDADB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PDADB', FILENAME = N'C:\Users\riksm\PDADB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PDADB_log', FILENAME = N'C:\Users\riksm\PDADB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PDADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PDADB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PDADB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PDADB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PDADB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PDADB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PDADB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PDADB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PDADB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PDADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PDADB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PDADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PDADB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PDADB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PDADB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PDADB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PDADB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PDADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PDADB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PDADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PDADB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PDADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PDADB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PDADB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PDADB] SET  MULTI_USER 
GO

ALTER DATABASE [PDADB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PDADB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PDADB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PDADB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PDADB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PDADB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PDADB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PDADB] SET  READ_WRITE 
GO

